### ISSUE TITLE
navigation shifts slightly when moving from home page to either docs or examples pages

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/wcc#58]
## Type of Change

- Documentation / Website

## Summary
Noticed that when navigating from Home to either Docs or Examples pages, the header navigation shifts subtly.  It seems Home is the outlier, and Docs / Examples have the same styles.
<img width="1236" alt="Screen Shot 2022-06-08 at 09 06 26" src="https://user-images.githubusercontent.com/895923/172623908-8f8ce3fe-cbe8-4400-95d4-76f06791e3b1.png">

<img width="1263" alt="Screen Shot 2022-06-08 at 09 05 54" src="https://user-images.githubusercontent.com/895923/172623803-1ff2a7b4-d7ec-4162-b3c4-87474826efe2.png">

## Details
I wonder if the difference is that Docs and Examples have markdown generated table of contents?  🤔

**Comment by soumya-78** [comment]
I will work on this, Can i be assigned this issue?

**Comment by thescientist13** [comment]
Hi @soumya-78 , I can't seem to reproduce it anymore, maybe I just had a zooming issue on my browsers?.  But if you are able to reproduce and can share that, then for sure a fix would be appreciated! 🙏

**Comment by thescientist13** [comment]
Tried some more testing and was unable to reproduce still, so maybe I was just seeing things?  Let me know if you still and in what browser so we can get it fixed if so.  Otherwise, will likely be able to close this one out, but there are definitely other good first issues that are up for grabs if you feel like it.  👍

**Comment by soumya-78** [comment]
I am unable to fix it. I tried to open it in two more browsers but facing the same issue..
looking forward to other good first issues.

**Comment by thescientist13** [comment]
Ok, sounds like it was just an issue on my end then, so good to know it's no longer a problem!  Phew.

Here is a link to some [good first issues](https://github.com/ProjectEvergreen/wcc/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) I have labeled, feel free to comment on anything that seems like you might be interested in working on.  🙏
